name: Deploy

on:
    push:
        branches: [master]

env:
    AWS_REGION: eu-central-1

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: AWS - Personal
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-region: ${{env.AWS_REGION}}
                  role-to-assume: ${{secrets.AWS_ROLE}}
            - run: npm ci
            - run: npm run cdk -- deploy --require-approval never --outputs-file output.json
